#!/bin/bash

playerctl metadata -sfF "{{ title }}" 2> /dev/null |
	while read -r TITLE; do
		if [[ "$TITLE" = "Advertisement" ]]; then
			pactl set-sink-mute @DEFAULT_SINK@ true
		else
			pactl set-sink-mute @DEFAULT_SINK@ false
		fi
	done

